service: url-maker-sls

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
      - dev
    autostart: true
    lambda:
      mountCode: true

functions:
  hello:
    handler: handler.hello
